name: Enviar Notificación de Básquet

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      # Forzamos Node 24 para cumplir con los requisitos de GitHub de mayo 2026
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar dependencias
        run: npm install nodemailer

      - name: Ejecutar script de envío
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        # Nombre del archivo actualizado sin tilde
        run: node notificacion.mjs
