name: Enviar recordatoris partits

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instal·lar dependències
        run: npm install nodemailer
      - name: Executar script de notificacions
        run: node notify.js
        env:
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
